[package]
name = "cbor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = "0.2.0"
minicbor = "0.18.0"
serde_cbor = "0.11.2"
serde_json = "1.0.89"
serde-transcode = "1.1.1"
