#ifndef NAMESPACE_H_INCLUDED
#define NAMESPACE_H_INCLUDED

#ifndef NAMESPACE
#define NAMESPACE
#endif

#define NAMESPACE_CONCATENATE1(X, Y) X##Y
#define NAMESPACE_CONCATENATE2(X, Y) NAMESPACE_CONCATENATE1(X, Y)

#define NAMESPACED(X) NAMESPACE_CONCATENATE2(NAMESPACE, X)

#endif
